/* eslint-disable */
/**
 * Generated data model types.
 *
 * THIS FILE IS AUTOMATICALLY GENERATED AND SHOULD NOT BE EDITED.
 */

import type { DataModelFromSchemaDefinition } from "convex/server";
import type schema from "../schema";

export type DataModel = DataModelFromSchemaDefinition<typeof schema>;

export type Id<TableName extends keyof DataModel> = DataModel[TableName]["_id"];

export type Doc<TableName extends keyof DataModel> =
  DataModel[TableName]["document"];
