// Types are now generated by Convex in convex/_generated/dataModel.ts
// This file is kept for reference and custom frontend types

export type Achievement = {
  key: string
  title: string
  description: string
  icon: string
  earned: boolean
  color: string
}

export const GENRES = [
  'Fantasy',
  'Sci-Fi', 
  'Romance',
  'Mystery',
  'Horror',
  'Manga',
  'Webtoon',
  'Non-Fiction',
  'Biography',
  'Adventure',
  'Slice of Life',
  'Isekai'
] as const

export const ART_STYLES = [
  'Isekai',
  'Fantasy',
  'Slice of Life',
  'Webtoon',
  'Manga',
  'Sketch',
  'Digital',
  'Fan Art',
  'Original Character'
] as const

export const MOOD_COLORS = {
  inkPink: 'bg-inkPink',
  inkLime: 'bg-inkLime',
  inkCyan: 'bg-inkCyan',
  inkPurple: 'bg-inkPurple',
  inkYellow: 'bg-inkYellow'
} as const

export const RATING_TYPES = {
  stars: { icon: '⭐', empty: '☆', label: 'Stars', max: 5 },
  hearts: { icon: '❤️', empty: '🤍', label: 'Hearts', max: 5 },
  books: { icon: '📚', empty: '📖', label: 'Books', max: 5 },
  sparkles: { icon: '✨', empty: '💫', label: 'Sparkles', max: 5 },
  flames: { icon: '🔥', empty: '🕯️', label: 'Fire', max: 5 },
  cats: { icon: '😺', empty: '🐱', label: 'Cats', max: 5 },
  rainbows: { icon: '🌈', empty: '☁️', label: 'Rainbows', max: 5 },
  cookies: { icon: '🍪', empty: '🥠', label: 'Cookies', max: 5 },
  thumbsUp: { icon: '👍', empty: '👎', label: 'Thumbs', max: 1 },
} as const

export type RatingType = keyof typeof RATING_TYPES

export const CHILD_FRIENDLY_EMOJI_CATEGORIES = [
  'people',
  'nature', 
  'foods',
  'activity',
  'objects',
  'symbols',
  'flags'
] as const

export const STICKER_PACKS = {
  reading: {
    name: 'Reading Time',
    stickers: ['📚', '📖', '📕', '📗', '📘', '📙', '🔖', '📑', '✏️', '🖊️', '📝', '💭']
  },
  feelings: {
    name: 'Book Feelings', 
    stickers: ['🥰', '😍', '🤩', '😭', '😱', '🤯', '💕', '💖', '💗', '✨', '🌟', '⭐']
  },
  animals: {
    name: 'Cute Animals',
    stickers: ['🐱', '🐶', '🐰', '🦊', '🐻', '🐼', '🦋', '🐝', '🌸', '🌺', '🌻', '🌷']
  },
  magic: {
    name: 'Magic & Fantasy',
    stickers: ['🧙', '🧚', '🦄', '🐉', '🏰', '👑', '🗡️', '🛡️', '🔮', '🪄', '⚡', '🌙']
  }
} as const