// Types are now generated by Convex in convex/_generated/dataModel.ts
// This file is kept for reference and custom frontend types

export type Achievement = {
  key: string
  title: string
  description: string
  icon: string
  earned: boolean
  color: string
}

export const GENRES = [
  'Fantasy',
  'Sci-Fi', 
  'Romance',
  'Mystery',
  'Horror',
  'Manga',
  'Webtoon',
  'Non-Fiction',
  'Biography',
  'Adventure',
  'Slice of Life',
  'Isekai'
] as const

export const ART_STYLES = [
  'Isekai',
  'Fantasy',
  'Slice of Life',
  'Webtoon',
  'Manga',
  'Sketch',
  'Digital',
  'Fan Art',
  'Original Character'
] as const

export const MOOD_COLORS = {
  inkPink: 'bg-inkPink',
  inkLime: 'bg-inkLime',
  inkCyan: 'bg-inkCyan',
  inkPurple: 'bg-inkPurple',
  inkYellow: 'bg-inkYellow'
} as const